<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{



    public function findAllCateriesforApi()
    {
        $builder = $this
            ->createQueryBuilder('c')
            ->getQuery()
            ->getResult();

        return $builder;
    }

}
